import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

type CreatePostWizardProps = {
  id?: string;
};

const CreatePostWizard: React.FC<CreatePostWizardProps> = () => {
  const { user } = useUser();

  if (!user) return null;

  return (
    <div>
      <img className="h-14 w-16 rounded-full" src={user.profileImageUrl}></img>
    </div>
  );
};

const Home: NextPage = () => {
  const user = useUser();
  const { data: posts, isLoading } = api.post.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;

  if (!posts) return <div>Something wong</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center bg-gray-800 text-white">
        <div className="w-full border-x border-slate-200 md:max-w-3xl">
          <div className="flex border-b border-slate-200 p-4">
            <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
            <div>{!user.isSignedIn && <SignInButton />}</div>
            <div>
              {user.isSignedIn && (
                <div>
                  <CreatePostWizard />
                  <SignOutButton />
                </div>
              )}
            </div>
          </div>

          <div className="space-y-4">
            {posts?.map((post) => (
              <div key={post.id} className="border-b border-slate-200 p-8">
                {post.content}
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
